name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lldd lld cmake
        pip install --upgrade pip
        pip install buildozer cython virtualenv kivy

    - name: Build with Buildozer
      run: |
        buildozer android debug
      env:
        ACCEPT_SDK_LICENSE: "y"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: QuantumChat-APK
        path: bin/*.apk

